### ISSUE TITLE
I am not an expert

### ISSUE THREAD

**Issue by TexAafke** [sayontan/suffusion#88] opened 2024-07-11 09:55 UTC
What should I do when this is the error?

Een fout van het type E_ERROR werd veroorzaakt op regelnummer 164 van het bestand /var/www/domains/aafkeprinsen.nl/www/wp-content/themes/suffusion/widgets/suffusion-query-posts.php. Foutmelding: Uncaught Error: Call to undefined function suffusion_get_image() in /var/www/domains/aafkeprinsen.nl/www/wp-content/themes/suffusion/widgets/suffusion-query-posts.php:164
Stack trace:
#0 /var/www/domains/aafkeprinsen.nl/www/wp-includes/class-wp-widget.php(394): Suffusion_Category_Posts->widget(Array, Array)
#1 /var/www/domains/aafkeprinsen.nl/www/wp-includes/widgets.php(2033): WP_Widget->display_callback(Array, Array)
#2 /var/www/domains/aafkeprinsen.nl/www/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php(697): wp_render_widget('suf-cat-posts-3', 'sidebar-13')
#3 /var/www/domains/aafkeprinsen.nl/www/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php(154): WP_REST_Widgets_Controller->prepare_item_for_response(Array, Object(WP_REST_Request))
#4 /var/www/domains/aafkeprinsen.nl/www/wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Widgets_Controller->get_items(Object(WP_REST_Request))
#5 /var/www/domains/aafkeprinsen.nl/www/wp-includes/rest-api/class-wp-rest-server.

I am just using the theme, not an expert. Thanks

**Comment by mbtools** [comment] 2024-07-11 22:21
Let's start with some details: Which version of WordPress do you have? What's the version of the suffusion theme?

What steps do you take to get the error message?

**Comment by TexAafke** [comment] 2024-07-14 14:47
I have it all updated. Newest Wordpress. Newest Suffusion. This error report came by mail. Site won't let me normally work with widgets anymore. Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Marc Bernard ***@***.***> Datum: 12-07-24  00:22  (GMT+01:00) Aan: sayontan/suffusion ***@***.***> Cc: TexAafke ***@***.***>, Author ***@***.***> Onderwerp: Re: [sayontan/suffusion] I am not an expert (Issue #88) 
Let's start with some details: Which version of WordPress do you have? What's the version of the suffusion theme?
What steps do you take to get the error message?

**Comment by TexAafke** [comment] 2024-07-14 14:48
Wordpress 6.5.5Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Marc Bernard ***@***.***> Datum: 12-07-24  00:22  (GMT+01:00) Aan: sayontan/suffusion ***@***.***> Cc: TexAafke ***@***.***>, Author ***@***.***> Onderwerp: Re: [sayontan/suffusion] I am not an expert (Issue #88) 
Let's start with some details: Which version of WordPress do you have? What's the version of the suffusion theme?
What steps do you take to get the error message?

**Comment by mbtools** [comment] 2024-07-14 21:54
I'm using the same versions on my site and widgets are working fine. 

The function `suffusion_get_image()` mentioned in the error message certainly exists (in `functions/media.php`) and that file is required properly by the Suffusion framework. Are you able to check if `media.php` exists in the theme/functions folder?

You wrote that widgets don't work anymore. So widgets were working before? What has changed?

**Comment by mbrsolution** [comment] 2024-07-21 00:56
Hello all, I can confirm that Suffusion works with the latest WordPress version 6.6. I am running Suffusion in one of my dev sites without any issues with the widgets. I recommend that you also install the following plugin because Suffusion does not work well with Gutenberg.

[https://wordpress.org/plugins/gutenberg/](url)

Kind regards,
Manuel

**Comment by fbrick1** [comment] 2024-07-21 14:46
***@***.***


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by marcissimus** [comment] 2024-09-21 20:29
No progress. Closing

**Closed by marcissimus** 2024-09-21 20:29 UTC
